server:
  address: 127.0.0.1
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
